apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app.kubernetes.io/name: account-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: account-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-service
    spec:
      containers:
      - name: account-service
        image: taycurran/account-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: management
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: SPRING_PROFILES_ACTIVE
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: SERVER_PORT
        - name: MANAGEMENT_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: MANAGEMENT_SERVER_PORT
        - name: DB_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: DB_POOL_SIZE
        - name: DB_CONNECTION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: DB_CONNECTION_TIMEOUT
        - name: DB_IDLE_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: DB_IDLE_TIMEOUT
        - name: EUREKA_CLIENT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: EUREKA_CLIENT_ENABLED
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: EUREKA_INSTANCE_HOSTNAME
        - name: NEWRELIC_ENABLED
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: NEWRELIC_ENABLED
        - name: DATADOG_TRACE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: account-service-config
              key: DATADOG_TRACE_ENABLED
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: account-service-creds
              key: DATABASE_URL
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
