apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app.kubernetes.io/name: account-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: account-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 8081
    targetPort: 8081
    protocol: TCP
