apiVersion: apps/v1
kind: Deployment
metadata:
  name: pe-eng-account-service-prod
  namespace: demo-apps
  labels:
    app: account-service
    app.kubernetes.io/name: account-service
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/part-of: retail-banking
    environment: prod
    managed-by: openshift
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
        app.kubernetes.io/name: account-service
        app.kubernetes.io/version: "1.2.0"
        app.kubernetes.io/part-of: retail-banking
        environment: prod
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: account-service
        image: registry.bank.internal/account-service:1.2.0@sha256:def456abc789123
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: management
        envFrom:
        - configMapRef:
            name: account-service-config
        - secretRef:
            name: account-service-secrets
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
