apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-service.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "account-service.selectorLabels" . | nindent 6 }}
      environment: {{ .Values.app.environment }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "account-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Values.app.version | quote }}
        app.kubernetes.io/part-of: {{ .Values.app.partOf }}
        environment: {{ .Values.app.environment }}
        managed-by: {{ .Values.app.managedBy }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "account-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.service.managementPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "account-service.fullname" . }}-config
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ .Values.secrets.name }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-storage
              mountPath: /tmp
            - name: app-logs
              mountPath: /tmp/app-logs
      volumes:
        - name: tmp-storage
          {{- toYaml .Values.volumes.tmpStorage | nindent 10 }}
        - name: app-logs
          {{- toYaml .Values.volumes.appLogs | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
