apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.managementPort }}
    targetPort: {{ .Values.service.managementPort }}
    protocol: TCP
    name: management
  selector:
    {{- include "account-service.selectorLabels" . | nindent 4 }}
