replicaCount: 3

image:
  repository: account-service
  pullPolicy: IfNotPresent
  tag: "1.2.0"

nameOverride: ""
fullnameOverride: ""

namespace:
  create: false
  name: demo-apps

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  managementPort: 8081

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: account-service.localhost
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  seccompProfile:
    type: RuntimeDefault
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

config:
  springProfilesActive: "production"
  serverPort: "8080"
  managementServerPort: "8081"
  dbPoolSize: "20"
  dbConnectionTimeout: "30000"
  dbIdleTimeout: "600000"
  eurekaClientEnabled: "true"
  eurekaInstanceHostname: "account-service"
  newrelicEnabled: "true"
  datadogTraceEnabled: "true"

secrets:
  databaseUrl: "jdbc:h2:mem:testdb"
  databaseUsername: "sa"
  databasePassword: ""
  redisUrl: "redis://localhost:6379"
  eurekaServiceUrl: "http://localhost:8761/eureka"
  configServerUrl: "http://localhost:8888"

environment: "dev"
